# Generated by Django 5.1.3 on 2024-11-10 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacky', '0003_resume_achievements_resume_advantages_resume_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Общий рейтинг'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['rating'], name='hacky_resum_rating_9c3ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['location'], name='hacky_resum_locatio_241bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['uploaded_at'], name='hacky_resum_uploade_b3125a_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['full_name'], name='hacky_resum_full_na_a6b87d_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['rating', 'location'], name='hacky_resum_rating_0d432a_idx'),
        ),
    ]
